name: chatapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  get: ^4.7.2
  get_it: ^9.0.5
  injectable: ^2.6.0
  sqflite: ^2.4.2
  firebase_ui_auth: ^3.0.1
  build_runner: ^2.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.9.1

flutter:
  uses-material-design: true
