name: wetopian_auth
description: "Wetopian Auth Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_it: ^7.6.7
  injectable: ^2.3.2
  http: ^1.1.0
  url_launcher: ^6.2.2
  flutter_secure_storage: ^9.2.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  injectable_generator: ^2.4.2
  

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/splash.jpg

  # If you have fonts, include them here
  # fonts:
  #   - family: SomeFont
  #     fonts:
  #       - asset: fonts/SomeFont-Regular.ttf